server:
  port: 8080
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  http:
    encoding.charset: UTF-8
    encoding.force: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/kin_scheduler?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 0
      minIdle: 0
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 10000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: 'stat,wall'
      validation-query: SELECT 1
    # 数据库有表就不执行
    # 可以定义你的建库文件
    schema: classpath:schema.sql
    # 可以定义你的数据文件
    #    data: classpath:data.sql
    # 有了错误是否继续运行
    #    continueOnError: false
    # 每次都初始化
  #    initialization-mode: always
  # mail
  mail:
    host: smtp.qq.com
    port: 25
    #    username:
    # 填授权码
    #    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          socketFactory.class: javax.net.ssl.SSLSocketFactory
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  resources:
    static-locations: classpath:/static

  # 格式化输出的json字符串
  jackson:
    serialization:
      indent_output: true
  # 缓存
  cache:
    ehcache:
      config: classpath:ehcache.xml

# mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml

# actuator
management:
  server:
    port: 8081
  endpoints:
    web:
      # 默认是 /actuator
      base-path: /monitor
      exposure:
        # 开放所有页面节点  默认只开启了health、info两个节点
        include: "*"
  endpoint:
    health:
      # 显示健康具体信息  默认不会显示详细信息
      show-details: always

# 应用配置
kin:
  scheduler:
    # admin 配置
    parallism: 5
    host: 0.0.0.0
    port: 46668
    logPath: logs
    serialize: kryo
    compression: false
    # scheduler core 配置
    workerHost: 0.0.0.0
    workerPort: 50000
    masterHost: 0.0.0.0
    masterPort: 46668
    allowEmbeddedExecutor: true
    executorPort: 51000
    heartbeat: 3000
#    CPU: 3

